In [1]:
import pandas as pd
from statsmodels.tsa.seasonal import seasonal_decompose

In [60]:
# make key
def make_key(time):
    key = str(time.month) + "-" + str(time.day) + "-" + str(time.hour) 
    return key

In [33]:
data = pd.read_csv('ten_airports_num_of_flights.csv', dtype='str')
data['time'] = pd.to_datetime(data['time'])

In [34]:
data.shape

(349897, 3)

In [35]:
data.head()

                 time flight_numbers airport
0 2015-01-01 00:00:00              0     ATL
1 2015-01-01 00:15:00              0     ATL
2 2015-01-01 00:30:00              0     ATL
3 2015-01-01 00:45:00              0     ATL
4 2015-01-01 01:00:00              0     ATL

In [36]:
airports = data['airport'].unique()

In [147]:
def get_final_data(airport, weather, airport_name):
    # select the columns, add the key
    weather = weather[['icon', 'temperature', 'windSpeed', 'visibility', 'summary', 'time']]
    weather['time'] = pd.to_datetime(weather['time'])
    weather['key'] = weather['time'].apply(make_key)
    
    # add key
    airport['time'] = pd.to_datetime(airport['time'])
    airport['key'] = airport['time'].apply(make_key)
    
    # merge the airport flight data and weather
    merged = pd.merge(airport, weather, on='key', how='left')
    merged = merged.drop('key', axis=1)
    merged = merged.rename(columns={'time_x':'flight_time', 'time_y':'weather_time'})
    
    merged.to_csv('#of_flights_with_weather/'+airport_name+'_final_data1.csv', index=False)
    
    return merged

In [128]:
airports = data['airport'].unique()
for airport in airports:
    df_sub = data[data['airport'] == airport]

In [154]:
airports

array(['ATL', 'DEN', 'DFW', 'IAH', 'LAS', 'LAX', 'MSP', 'ORD', 'PHX',
       'SFO'], dtype=object)

In [152]:
def get_weather(name):
    df = pd.read_csv('weather_data/'+name+'_weather.csv')
    return df

In [153]:
for i in airports:
    weather = get_weather(i)
    airport_final_data = get_columns(data[data['airport'] == i], weather, i)

C:\Users\gnaci\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\gnaci\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """
C:\Users\gnaci\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\gnaci\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

# sample data selected randomly as DFW

In [160]:
dfw = pd.read_csv('final_data/DFW_final_data1.csv')

In [161]:
dfw

,flight_time,flight_numbers,airport,icon,temperature,windSpeed,visibility,summary,weather_time
0,2015-01-01 00:00:00,0,DFW,cloudy,33.43,3.27,10.00,Overcast,2015-01-01 00:00:00
1,2015-01-01 00:15:00,0,DFW,cloudy,33.43,3.27,10.00,Overcast,2015-01-01 00:00:00
2,2015-01-01 00:30:00,0,DFW,cloudy,33.43,3.27,10.00,Overcast,2015-01-01 00:00:00
3,2015-01-01 00:45:00,0,DFW,cloudy,33.43,3.27,10.00,Overcast,2015-01-01 00:00:00
4,2015-01-01 01:00:00,0,DFW,cloudy,33.43,2.25,10.00,Overcast,2015-01-01 01:00:00
5,2015-01-01 01:15:00,0,DFW,cloudy,33.43,2.25,10.00,Overcast,2015-01-01 01:00:00
6,2015-01-01 01:30:00,0,DFW,cloudy,33.43,2.25,10.00,Overcast,2015-01-01 01:00:00
7,2015-01-01 01:45:00,0,DFW,cloudy,33.43,2.25,10.00,Overcast,2015-01-01 01:00:00
8,2015-01-01 02:00:00,0,DFW,cloudy,33.59,1.87,10.00,Overcast,2015-01-01 02:00:00
9,2015-01-01 02:15:00,0,DFW,cloudy,33.59,1.87,10.00,Overcast,2015-01-01 02:00:00
10,2015-01-01 02:30:00,0,DFW,cloudy,33.59,1.87,10.00,Overcast,2015-01-01 02:00:00
11,2015-01-01 02:45:00,0,DFW,cloudy,33.59,1.87,10.00,Overcast,2015-01-01 02:00:00
12,2015-01-01 03:00:00,0,DFW,cloudy,33.66,1.65,10.00,Overcast,2015-01-01 03:00:00
13,2015-01-01 03:15:00,0,DFW,cloudy,33.66,1.65,10.00,Overcast,2015-01-01 03:00:00
14,2015-01-01 03:30:00,0,DFW,cloudy,33.66,1.65,10.00,Overcast,2015-01-01 03:00:00
15,2015-01-01 03:45:00,0,DFW,cloudy,33.66,1.65,10.00,Overcast,2015-01-01 03:00:00
16,2015-01-01 04:00:00,0,DFW,cloudy,33.82,1.30,10.00,Overcast,2015-01-01 04:00:00
17,2015-01-01 04:15:00,0,DFW,cloudy,33.82,1.30,10.00,Overcast,2015-01-01 04:00:00
18,2015-01-01 04:30:00,0,DFW,cloudy,33.82,1.30,10.00,Overcast,2015-01-01 04:00:00
19,2015-01-01 04:45:00,0,DFW,cloudy,33.82,1.30,10.00,Overcast,2015-01-01 04:00:00
20,2015-01-01 05:00:00,0,DFW,cloudy,33.83,1.22,10.00,Overcast,2015-01-01 05:00:00
21,2015-01-01 05:15:00,1,DFW,cloudy,33.83,1.22,10.00,Overcast,2015-01-01 05:00:00
22,2015-01-01 05:30:00,0,DFW,cloudy,33.83,1.22,10.00,Overcast,2015-01-01 05:00:00
23,2015-01-01 05:45:00,1,DFW,cloudy,33.83,1.22,10.00,Overcast,2015-01-01 05:00:00
24,2015-01-01 06:00:00,9,DFW,cloudy,33.63,1.50,9.67,Overcast,2015-01-01 06:00:00
25,2015-01-01 06:15:00,5,DFW,cloudy,33.63,1.50,9.67,Overcast,2015-01-01 06:00:00
26,2015-01-01 06:30:00,0,DFW,cloudy,33.63,1.50,9.67,Overcast,2015-01-01 06:00:00
27,2015-01-01 06:45:00,5,DFW,cloudy,33.63,1.50,9.67,Overcast,2015-01-01 06:00:00
28,2015-01-01 07:00:00,8,DFW,cloudy,33.43,0.82,9.15,Overcast,2015-01-01 07:00:00
29,2015-01-01 07:15:00,8,DFW,cloudy,33.43,0.82,9.15,Overcast,2015-01-01 07:00:00
...,...,...,...,...,...,...,...,...,...
34919,2015-12-30 17:45:00,5,DFW,partly-cloudy-day,45.30,1.78,10.00,Partly Cloudy,2015-12-30 17:00:00
34920,2015-12-30 18:00:00,3,DFW,clear-day,47.55,1.75,10.00,Clear,2015-12-30 18:00:00
34921,2015-12-30 18:15:00,13,DFW,clear-day,47.55,1.75,10.00,Clear,2015-12-30 18:00:00
34922,2015-12-30 18:30:00,18,DFW,clear-day,47.55,1.75,10.00,Clear,2015-12-30 18:00:00
34923,2015-12-30 18:45:00,27,DFW,clear-day,47.55,1.75,10.00,Clear,2015-12-30 18:00:00
34924,2015-12-30 19:00:00,6,DFW,clear-day,49.53,2.16,10.00,Clear,2015-12-30 19:00:00
34925,2015-12-30 19:15:00,4,DFW,clear-day,49.53,2.16,10.00,Clear,2015-12-30 19:00:00
34926,2015-12-30 19:30:00,3,DFW,clear-day,49.53,2.16,10.00,Clear,2015-12-30 19:00:00
34927,2015-12-30 19:45:00,4,DFW,clear-day,49.53,2.16,10.00,Clear,2015-12-30 19:00:00
34928,2015-12-30 20:00:00,19,DFW,partly-cloudy-day,50.91,1.92,10.00,Partly Cloudy,2015-12-30 20:00:00
34929,2015-12-30 20:15:00,28,DFW,partly-cloudy-day,50.91,1.92,10.00,Partly Cloudy,2015-12-30 20:00:00
34930,2015-12-30 20:30:00,11,DFW,partly-cloudy-day,50.91,1.92,10.00,Partly Cloudy,2015-12-30 20:00:00
34931,2015-12-30 20:45:00,3,DFW,partly-cloudy-day,50.91,1.92,10.00,Partly Cloudy,2015-12-30 20:00:00
34932,2015-12-30 21:00:00,1,DFW,clear-day,51.68,1.23,10.00,Clear,2015-12-30 21:00:00
34933,2015-12-30 21:15:00,2,DFW,clear-day,51.68,1.23,10.00,Clear,2015-12-30 21:00:00
34934,2015-12-30 21:30:00,0,DFW,clear-day,51.68,1.23,10.00,Clear,2015-12-30 21:00:00
34935,2015-12-30 21:45:00,22,DFW,clear-day,51.68,1.23,10.00,Clear,2015-12-30 21:00:00
34936,2015-12-30 22:00:00,16,DFW,clear-day,51.84,1.01,10.00,Clear,2015-12-30 22:00:00
34937,2015-12-30 22:15:00,5,DFW,clear-day,51.84,1.01,10.00,Clear,2015-12-30 22:00:00
34938,2015-12-30 22:30:00,2,DFW,clear-day,51.84,1.01,10.00,Clear,2015-12-30 22:00:00
34939,2015-12-30 22:45:00,0,DFW,clear-day,51.84,1.01,10.00,Clear,2015-12-30 22:00:00
34940,2015-12-30 23:00:00,1,DFW,clear-day,50.35,0.73,10.00,Clear,2015-12-30 23:00:00
34941,2015-12-30 23:15:00,1,DFW,clear-day,50.35,0.73,10.00,Clear,2015-12-30 23:00:00
34942,2015-12-30 23:30:00,0,DFW,clear-day,50.35,0.73,10.00,Clear,2015-12-30 23:00:00
34943,2015-12-30 23:45:00,0,DFW,clear-day,50.35,0.73,10.00,Clear,2015-12-30 23:00:00
34944,2015-12-31 00:00:00,0,DFW,clear-night,47.42,0.32,10.00,Clear,2015-12-31 00:00:00
34945,2015-12-31 05:00:00,2,DFW,clear-night,39.32,0.01,9.68,Clear,2015-12-31 05:00:00
34946,2015-12-31 05:15:00,1,DFW,clear-night,39.32,0.01,9.68,Clear,2015-12-31 05:00:00
34947,2015-12-31 05:30:00,1,DFW,clear-night,39.32,0.01,9.68,Clear,2015-12-31 05:00:00
34948,2015-12-31 05:45:00,2,DFW,clear-night,39.32,0.01,9.68,Clear,2015-12-31 05:00:00